import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  Bell,
  Boxes,
  Building2,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Cpu,
  Database,
  Droplets,
  FileBarChart,
  FileText,
  Fuel,
  Gauge,
  GitBranch,
  History,
  LayoutDashboard,
  LifeBuoy,
  ListTree,
  type LucideIcon,
  MapPin,
  Monitor,
  Moon,
  Plug,
  Radar,
  RefreshCw,
  Route,
  Settings,
  Shield,
  Sliders,
  Sun,
  Target,
  Thermometer,
  Truck,
  UserCog,
  Users,
  Waves,
  Wifi,
  WifiOff,
  Plus,
  Search,
  Download,
  Filter,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Play,
  Pause,
  Trash2,
  Pencil,
  Eye,
  Calendar,
  Link2,
  KeyRound,
  Printer,
  Info,
  Minus,
} from "lucide-react";

export const icons = {
  dashboard: LayoutDashboard,
  station: Building2,
  tank: Droplets,
  fuel: Fuel,
  movement: ArrowLeftRight,
  refuel: Waves,
  consumption: Activity,
  transactions: ListTree,
  alert: AlertTriangle,
  bell: Bell,
  report: FileBarChart,
  reportText: FileText,
  device: Cpu,
  radar: Radar,
  plug: Plug,
  vehicle: Truck,
  route: Route,
  map: MapPin,
  users: Users,
  user: UserCog,
  shield: Shield,
  settings: Settings,
  sliders: Sliders,
  gauge: Gauge,
  target: Target,
  history: History,
  audit: ClipboardList,
  integration: Plug,
  database: Database,
  org: Building2,
  box: Boxes,
  temp: Thermometer,
  clock: Clock,
  wifi: Wifi,
  wifiOff: WifiOff,
  refresh: RefreshCw,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  branch: GitBranch,
  currency: CircleDollarSign,
  support: LifeBuoy,
  plus: Plus,
  search: Search,
  download: Download,
  filter: Filter,
  close: X,
  check: Check,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  play: Play,
  pause: Pause,
  trash: Trash2,
  edit: Pencil,
  eye: Eye,
  calendar: Calendar,
  water: Waves,
  speed: Gauge,
  link: Link2,
  key: KeyRound,
  building: Building2,
  location: MapPin,
  printer: Printer,
  info: Info,
  minus: Minus,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = icons[name];
  return <Component className={className} aria-hidden="true" />;
}
